### ISSUE TITLE
Discuss: new features and wish lists

### ISSUE THREAD

**Issue by davidruvolo51** [davidruvolo51/yaml-emx-convert#1]
## Features

- [x] **Import base EMX markup in YAML file**: In some scenarios, you may be creating multiple tables within a package or subpackage. These tables may share the same base EMX structure. Rather than copying and pasting this information in multiple files (which defeats the purpose of this package), it would nice to have an option to include a base structure. I think adding another highlevel attribute (i.e., `include: path/to/base.yaml`) would be nice to have.
-  ~**Templates**: (Applies to `entities > attributes`) I would like to have the option to create a default set of attributes that can be applied to multiple entities within a package where specified. For example, there are situations where many tables have ID, name, group, description, etc. I would like to have a place to define them once and have an attribute `template` that inserts the attributes where I need them. This would save time and also prevent inconsistencies across the tables.~

**Comment by davidruvolo51** [comment]
For templates, I would like to structure the markup like so:

```yaml
name: data
label: Project data
description: Repository for project data
version: 1.12.1224
date: 2021-09-21


templates:
    - name: ids
      attributes:
        - name: id
          label: ID
          description: Unique record identifier
         dataType: int
         idAttribute: true
        - name: group
          dataType: mref
          refEntity: data_groups
        - name: value
          dataType: decimal

entities:
    - name: participants
      attributes:
        - template: ids
        - name: dateRegistered
          dataType: datetime
      ...
    - groups:
      ...
```
